import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Header } from "@/components/Header";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Download, Loader2, Search, Users, Sparkles, TrendingUp } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";

export const Route = createFileRoute("/submissions")({
  head: () => ({
    meta: [
      { title: "Submissions Dashboard — PathwayAI" },
      { name: "description", content: "Browse, filter and export all academic pathway submissions." },
    ],
  }),
  component: SubmissionsPage,
});

interface Submission {
  id: string;
  full_name: string;
  email: string;
  qualification: string;
  work_experience: number;
  profession: string;
  career_goal: string;
  recommendation: string;
  created_at: string;
}

const RECS = ["All", "Certification Program", "DBA (Doctor of Business Administration)", "PhD", "Honorary Doctorate"];

function SubmissionsPage() {
  const [search, setSearch] = useState("");
  const [filter, setFilter] = useState("All");

  const { data, isLoading, error } = useQuery({
    queryKey: ["submissions"],
    queryFn: async (): Promise<Submission[]> => {
      const { data, error } = await supabase
        .from("submissions")
        .select("*")
        .order("created_at", { ascending: false });
      if (error) throw error;
      return data as Submission[];
    },
  });

  const filtered = useMemo(() => {
    if (!data) return [];
    const q = search.toLowerCase().trim();
    return data.filter((s) => {
      const matchesQ = !q || s.full_name.toLowerCase().includes(q) || s.email.toLowerCase().includes(q) || s.profession.toLowerCase().includes(q) || s.career_goal.toLowerCase().includes(q);
      const matchesF = filter === "All" || s.recommendation === filter;
      return matchesQ && matchesF;
    });
  }, [data, search, filter]);

  const stats = useMemo(() => {
    const list = data ?? [];
    const counts: Record<string, number> = {};
    for (const s of list) counts[s.recommendation] = (counts[s.recommendation] ?? 0) + 1;
    const popular = Object.entries(counts).sort((a, b) => b[1] - a[1])[0]?.[0] ?? "—";
    return { total: list.length, kinds: Object.keys(counts).length, popular };
  }, [data]);

  const exportCsv = () => {
    const rows = filtered;
    if (rows.length === 0) return;
    const headers = ["Name", "Email", "Qualification", "Experience", "Profession", "Career Goal", "Recommendation", "Submitted"];
    const escape = (v: unknown) => `"${String(v ?? "").replace(/"/g, '""')}"`;
    const csv = [
      headers.join(","),
      ...rows.map((r) => [r.full_name, r.email, r.qualification, r.work_experience, r.profession, r.career_goal, r.recommendation, r.created_at].map(escape).join(",")),
    ].join("\n");
    const blob = new Blob([csv], { type: "text/csv;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `submissions-${new Date().toISOString().slice(0, 10)}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-background">
      <Header />
      <div className="container mx-auto px-4 py-10 sm:py-14">
        <div className="flex flex-wrap items-end justify-between gap-4">
          <div>
            <h1 className="text-3xl font-semibold tracking-tight sm:text-4xl">Submissions</h1>
            <p className="mt-2 text-muted-foreground">All recommendations generated by users.</p>
          </div>
          <Button onClick={exportCsv} variant="outline" className="rounded-full" disabled={filtered.length === 0}>
            <Download className="mr-2 h-4 w-4" /> Export CSV
          </Button>
        </div>

        {/* Stats */}
        <div className="mt-8 grid gap-4 sm:grid-cols-3">
          <StatCard icon={Users} label="Total Users" value={stats.total} />
          <StatCard icon={Sparkles} label="Recommendations Issued" value={stats.total} />
          <StatCard icon={TrendingUp} label="Most Popular" value={stats.popular} small />
        </div>

        {/* Filters */}
        <div className="mt-8 flex flex-wrap items-center gap-3 rounded-2xl border border-border bg-card p-3 shadow-card">
          <div className="relative flex-1 min-w-[220px]">
            <Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
            <Input
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              placeholder="Search by name, email, profession, or goal..."
              className="pl-9"
            />
          </div>
          <Select value={filter} onValueChange={setFilter}>
            <SelectTrigger className="w-[260px]">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {RECS.map((r) => (
                <SelectItem key={r} value={r}>{r}</SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>

        {/* Table */}
        <div className="mt-6 overflow-hidden rounded-2xl border border-border bg-card shadow-card">
          {isLoading ? (
            <div className="flex items-center justify-center py-20 text-muted-foreground">
              <Loader2 className="mr-2 h-5 w-5 animate-spin" /> Loading submissions...
            </div>
          ) : error ? (
            <div className="py-20 text-center text-destructive">Failed to load submissions.</div>
          ) : filtered.length === 0 ? (
            <div className="py-20 text-center text-muted-foreground">No submissions match your filters.</div>
          ) : (
            <div className="overflow-x-auto">
              <table className="min-w-full text-sm">
                <thead className="bg-muted/50 text-left text-xs uppercase tracking-wide text-muted-foreground">
                  <tr>
                    <th className="px-4 py-3 font-medium">Name</th>
                    <th className="px-4 py-3 font-medium">Email</th>
                    <th className="px-4 py-3 font-medium">Career Goal</th>
                    <th className="px-4 py-3 font-medium">Recommendation</th>
                    <th className="px-4 py-3 font-medium">Submitted</th>
                  </tr>
                </thead>
                <tbody>
                  {filtered.map((s) => (
                    <tr key={s.id} className="border-t border-border transition hover:bg-muted/30">
                      <td className="px-4 py-3 font-medium text-foreground">{s.full_name}</td>
                      <td className="px-4 py-3 text-muted-foreground">{s.email}</td>
                      <td className="px-4 py-3 max-w-md truncate text-muted-foreground" title={s.career_goal}>{s.career_goal}</td>
                      <td className="px-4 py-3">
                        <span className="inline-flex items-center rounded-full border border-primary/20 bg-primary/10 px-2.5 py-1 text-xs font-medium text-primary">
                          {s.recommendation}
                        </span>
                      </td>
                      <td className="px-4 py-3 text-muted-foreground">{new Date(s.created_at).toLocaleString()}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

function StatCard({ icon: Icon, label, value, small }: { icon: React.ComponentType<{ className?: string }>; label: string; value: string | number; small?: boolean }) {
  return (
    <div className="rounded-2xl border border-border bg-card p-5 shadow-card">
      <div className="flex items-center gap-3">
        <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-to-br from-primary/15 to-accent/15 text-primary">
          <Icon className="h-5 w-5" />
        </span>
        <div>
          <p className="text-xs uppercase tracking-wide text-muted-foreground">{label}</p>
          <p className={small ? "mt-1 text-base font-semibold text-foreground" : "mt-1 text-2xl font-semibold text-foreground"}>
            {value}
          </p>
        </div>
      </div>
    </div>
  );
}
